using System.Globalization;
using System.IO;
using System.Net;
using System.Text.Json;
using Julco.Cdp;

namespace Julco.UI;

public sealed record CaptureReportBranding(
    bool Enabled,
    string ProductName,
    string AccentColor,
    string LogoPath,
    string FooterText)
{
    public static CaptureReportBranding Default { get; } = new(
        false,
        "Julco",
        "#41c7ff",
        string.Empty,
        "Generated by Julco.");

    public CaptureReportBranding Normalized()
    {
        return this with
        {
            ProductName = string.IsNullOrWhiteSpace(ProductName) ? Default.ProductName : ProductName.Trim(),
            AccentColor = string.IsNullOrWhiteSpace(AccentColor) ? Default.AccentColor : AccentColor.Trim(),
            LogoPath = LogoPath?.Trim() ?? string.Empty,
            FooterText = string.IsNullOrWhiteSpace(FooterText) ? Default.FooterText : FooterText.Trim()
        };
    }
}

public sealed record CaptureReportRenderContext(
    CaptureReport Report,
    CaptureReportProfileTemplate Template,
    CaptureReportBranding Branding,
    string ExecutiveSummary)
{
    public static CaptureReportRenderContext CreateDefault(CaptureReport report)
    {
        return new CaptureReportRenderContext(
            report,
            CaptureReportProfileTemplate.FromReport(report),
            CaptureReportBranding.Default,
            CaptureReportExecutiveSummaryBuilder.Build(report));
    }
}

public static class CaptureReportTemplateStore
{
    private const string TemplatesDirectoryName = "report-templates";
    private const string BrandingFileName = ".julco-report-branding.json";
    private static readonly JsonSerializerOptions JsonOptions = new() { WriteIndented = true };

    public static CaptureReportRenderContext CreateContext(CaptureReport report)
    {
        var template = LoadTemplate(report);
        var branding = LoadBranding(report.CaptureDirectory);
        return new CaptureReportRenderContext(
            report,
            template,
            branding,
            CaptureReportExecutiveSummaryBuilder.Build(report));
    }

    private static CaptureReportProfileTemplate LoadTemplate(CaptureReport report)
    {
        var defaults = CaptureReportProfileTemplate.FromReport(report);
        var directory = Path.Combine(report.CaptureDirectory, TemplatesDirectoryName);
        Directory.CreateDirectory(directory);
        var path = Path.Combine(directory, $"{SanitizeTemplateName(defaults.Name)}.json");

        if (!File.Exists(path))
        {
            File.WriteAllText(path, JsonSerializer.Serialize(defaults, JsonOptions));
            return defaults;
        }

        try
        {
            return JsonSerializer.Deserialize<CaptureReportProfileTemplate>(File.ReadAllText(path))
                ?? defaults;
        }
        catch (JsonException)
        {
            return defaults;
        }
    }

    private static CaptureReportBranding LoadBranding(string captureDirectory)
    {
        var path = Path.Combine(captureDirectory, BrandingFileName);
        if (!File.Exists(path))
        {
            File.WriteAllText(path, JsonSerializer.Serialize(CaptureReportBranding.Default, JsonOptions));
            return CaptureReportBranding.Default;
        }

        try
        {
            return (JsonSerializer.Deserialize<CaptureReportBranding>(File.ReadAllText(path))
                ?? CaptureReportBranding.Default).Normalized();
        }
        catch (JsonException)
        {
            return CaptureReportBranding.Default;
        }
    }

    private static string SanitizeTemplateName(string value)
    {
        var invalid = Path.GetInvalidFileNameChars();
        var clean = new string(value.Select(character => invalid.Contains(character) ? '-' : character).ToArray());
        return string.IsNullOrWhiteSpace(clean) ? "default" : clean.Trim();
    }
}

public static class CaptureReportExecutiveSummaryBuilder
{
    public static string Build(CaptureReport report)
    {
        var issueLine = string.IsNullOrWhiteSpace(report.CommonIssues)
            ? "No common issue report was captured."
            : FirstMeaningfulLine(report.CommonIssues);
        var noteLine = report.Notes.HasContent
            ? report.Notes.ShortSummary
            : "No reviewer notes were added.";
        return string.Join(
            " ",
            $"Captured {report.TagName} on {Shorten(report.PageTitle, 70)} using {report.Browser}.",
            $"Frame {report.Frame.Width:0}x{report.Frame.Height:0} at {report.Frame.X:0},{report.Frame.Y:0}.",
            issueLine,
            noteLine);
    }

    private static string FirstMeaningfulLine(string text)
    {
        return text.ReplaceLineEndings("\n")
            .Split('\n', StringSplitOptions.RemoveEmptyEntries | StringSplitOptions.TrimEntries)
            .FirstOrDefault(line => !line.StartsWith("#", StringComparison.Ordinal))
            ?? "Common issue report is available.";
    }

    private static string Shorten(string? value, int maxLength)
    {
        if (string.IsNullOrWhiteSpace(value))
        {
            return "the selected page";
        }

        return value.Length <= maxLength ? value : value[..Math.Max(0, maxLength - 1)] + "...";
    }
}

public sealed class MarkdownReportRenderer
{
    public string Render(CaptureReportRenderContext context)
    {
        var report = context.Report;
        var template = context.Template;
        var lines = new List<string>
        {
            $"# {MarkdownLine(context.Branding.Enabled ? context.Branding.ProductName : "Julco")} Capture Report",
            string.Empty,
            $"**Page:** {MarkdownLine(report.PageTitle)}",
            $"**URL:** {MarkdownLine(report.PageUrl)}",
            $"**Created:** {report.CreatedAt:yyyy-MM-dd HH:mm:ss zzz}",
            $"**Profile:** {MarkdownLine(report.UsageProfile)}",
            $"**Profile focus:** {MarkdownLine(template.Focus)}",
            string.Empty,
            "## Executive Summary",
            string.Empty,
            MarkdownLine(context.ExecutiveSummary),
            string.Empty
        };

        if (!string.IsNullOrWhiteSpace(report.ScreenshotPath))
        {
            lines.Add("![Capture screenshot](../screenshot.png)");
            lines.Add(string.Empty);
        }

        lines.AddRange(BuildProfileMarkdown(template));
        foreach (var section in template.SectionOrder)
        {
            lines.AddRange(BuildMarkdownSection(report, section));
        }

        if (context.Branding.Enabled)
        {
            lines.Add("## Branding");
            lines.Add(string.Empty);
            lines.Add(MarkdownLine(context.Branding.FooterText));
            lines.Add(string.Empty);
        }

        return string.Join(Environment.NewLine, lines);
    }

    private static IReadOnlyList<string> BuildProfileMarkdown(CaptureReportProfileTemplate template)
    {
        return new[]
        {
            "## Profile Guidance",
            string.Empty,
            $"**Focus:** {MarkdownLine(template.Focus)}",
            string.Empty,
            "### Priority Signals",
            string.Empty
        }
        .Concat(template.PrioritySignals.Select(item => $"- {MarkdownLine(item)}"))
        .Concat(new[]
        {
            string.Empty,
            "### Review Checklist",
            string.Empty
        })
        .Concat(template.ReviewChecklist.Select(item => $"- [ ] {MarkdownLine(item)}"))
        .Concat(new[]
        {
            string.Empty,
            "### Recommended Next Steps",
            string.Empty
        })
        .Concat(template.RecommendedNextSteps.Select(item => $"- {MarkdownLine(item)}"))
        .Concat(new[] { string.Empty })
        .ToArray();
    }

    private static IReadOnlyList<string> BuildMarkdownSection(CaptureReport report, string section)
    {
        return section switch
        {
            "Technical" => new[]
            {
                "## Technical Summary",
                string.Empty,
                "| Field | Value |",
                "| --- | --- |",
                $"| Browser | {MarkdownLine(report.Browser)} |",
                $"| Remote port | {MarkdownLine(report.RemotePort)} |",
                $"| Target type | {MarkdownLine(report.TargetType)} |",
                $"| Profile | {MarkdownLine(report.UsageProfile)} |",
                $"| Element | `{MarkdownLine(report.TagName)}` |",
                $"| Selector | `{MarkdownLine(report.Selector)}` |",
                $"| Lens frame | {report.Frame.Width:0}x{report.Frame.Height:0} at {report.Frame.X:0},{report.Frame.Y:0} |",
                $"| Center | {report.Frame.CenterX:0},{report.Frame.CenterY:0} |",
                $"| Screen | {MarkdownLine(report.Frame.ScreenName)} {report.Frame.ScreenWidth}x{report.Frame.ScreenHeight} |",
                $"| Image resources | {report.Images.Count} |",
                string.Empty
            },
            "Notes" => new[] { "## Notes", string.Empty, report.Notes.HasContent ? report.Notes.ToMarkdown() : "_No notes added._", string.Empty },
            "Issues" => new[] { "## Common Issues", string.Empty, string.IsNullOrWhiteSpace(report.CommonIssues) ? "_No issue report found._" : report.CommonIssues, string.Empty },
            "Attributes" => new[] { "## Attributes", string.Empty, CodeBlock(report.Attributes, "text"), string.Empty },
            "CSS" => new[] { "## Computed CSS", string.Empty, CodeBlock(report.ComputedCss, "css"), string.Empty },
            "DOM" => new[] { "## DOM", string.Empty, CodeBlock(report.Dom, "html"), string.Empty },
            "Console" => new[] { "## Console", string.Empty, CodeBlock(string.IsNullOrWhiteSpace(report.Console) ? "No console messages captured." : report.Console, "text"), string.Empty },
            "Images" => BuildImagesMarkdownSection(report),
            _ => Array.Empty<string>()
        };
    }

    private static IReadOnlyList<string> BuildImagesMarkdownSection(CaptureReport report)
    {
        var lines = new List<string> { "## Image Resources", string.Empty };
        if (report.Images.Count == 0)
        {
            lines.Add("_No image resources detected._");
            lines.Add(string.Empty);
            return lines;
        }

        lines.Add("| Kind | Format | Shown | Natural | URL |");
        lines.Add("| --- | --- | --- | --- | --- |");
        lines.AddRange(report.Images.Take(80).Select(image =>
            $"| {MarkdownLine(image.Kind)} | {MarkdownLine(image.Format)} | {image.DisplayedWidth}x{image.DisplayedHeight} | {image.NaturalWidth}x{image.NaturalHeight} | `{MarkdownLine(Shorten(image.Url, 120))}` |"));
        lines.Add(string.Empty);
        return lines;
    }

    private static string CodeBlock(string content, string language)
    {
        return $"```{language}{Environment.NewLine}{content.Trim()}{Environment.NewLine}```";
    }

    private static string MarkdownLine(string? value) => CaptureReport.NormalizeMarkdownLine(value);

    private static string Shorten(string? value, int maxLength) => CaptureReportText.Shorten(value, maxLength);
}

public sealed class HtmlReportRenderer
{
    public string Render(CaptureReportRenderContext context)
    {
        var report = context.Report;
        var template = context.Template;
        var branding = context.Branding;
        var accent = EscapeCssColor(branding.Enabled ? branding.AccentColor : CaptureReportBranding.Default.AccentColor);
        var product = branding.Enabled ? branding.ProductName : "Julco";
        var screenshotMarkup = string.IsNullOrWhiteSpace(report.ScreenshotPath)
            ? "<div class=\"empty\">No screenshot found.</div>"
            : "<img class=\"screenshot\" src=\"../screenshot.png\" alt=\"Capture screenshot\" />";
        var notesMarkup = report.Notes.HasContent
            ? $"<dl>{Definition("Category", report.Notes.Category)}{Definition("Severity", report.Notes.Severity)}{Definition("Status", report.Notes.Status)}{Definition("Tags", report.Notes.Tags)}</dl><p>{Html(report.Notes.Observation)}</p>"
            : "<p class=\"empty\">No notes added.</p>";
        var imageRows = report.Images.Count == 0
            ? "<tr><td colspan=\"5\">No image resources detected.</td></tr>"
            : string.Join(Environment.NewLine, report.Images.Take(80).Select(image =>
                $"<tr><td>{Html(image.Kind)}</td><td>{Html(image.Format)}</td><td>{image.DisplayedWidth}x{image.DisplayedHeight}</td><td>{image.NaturalWidth}x{image.NaturalHeight}</td><td><code>{Html(CaptureReportText.Shorten(image.Url, 120))}</code></td></tr>"));
        var profileMarkup = BuildProfileHtml(template);
        var orderedSections = string.Join(Environment.NewLine, template.SectionOrder.Select(section => BuildHtmlSection(report, section, imageRows, notesMarkup)));
        var logoMarkup = branding.Enabled && !string.IsNullOrWhiteSpace(branding.LogoPath)
            ? $"<img class=\"brand-logo\" src=\"{Html(branding.LogoPath)}\" alt=\"{Html(product)} logo\" />"
            : string.Empty;

        return $$"""
            <!doctype html>
            <html lang="en">
            <head>
              <meta charset="utf-8" />
              <meta name="viewport" content="width=device-width, initial-scale=1" />
              <title>{{Html(product)}} Capture Report</title>
              <style>
                :root { color-scheme: dark; --bg:#0f1218; --panel:#181d26; --ink:#f5f7fb; --muted:#aeb8c8; --line:#2d3645; --accent:{{accent}}; --soft:#111722; }
                * { box-sizing: border-box; }
                body { margin:0; background:var(--bg); color:var(--ink); font:14px/1.55 "Segoe UI", Arial, sans-serif; }
                main { max-width:1120px; margin:0 auto; padding:32px; }
                header { border-bottom:1px solid var(--line); padding-bottom:18px; margin-bottom:24px; }
                h1 { margin:0 0 6px; font-size:30px; letter-spacing:0; }
                h2 { margin:0 0 12px; font-size:18px; color:var(--accent); }
                h3 { margin:16px 0 8px; font-size:14px; color:var(--ink); }
                .muted, footer { color:var(--muted); }
                .brand { display:flex; gap:14px; align-items:center; }
                .brand-logo { max-width:56px; max-height:56px; object-fit:contain; }
                .hero { display:grid; grid-template-columns:minmax(280px, 1.2fr) minmax(260px, .8fr); gap:18px; align-items:start; }
                .panel { background:var(--panel); border:1px solid var(--line); border-radius:8px; padding:18px; margin-bottom:18px; }
                .summary { border-left:3px solid var(--accent); }
                .screenshot { width:100%; max-height:520px; object-fit:contain; background:#05070a; border:1px solid var(--line); border-radius:6px; }
                dl { display:grid; grid-template-columns:130px 1fr; gap:8px 14px; margin:0; }
                dt { color:var(--muted); }
                dd { margin:0; word-break:break-word; }
                code, pre { font-family:Consolas, "Cascadia Mono", monospace; }
                pre { max-height:360px; overflow:auto; padding:14px; border-radius:6px; background:#05070a; border:1px solid var(--line); white-space:pre-wrap; }
                details summary { cursor:pointer; color:var(--accent); font-weight:600; margin:-2px 0 12px; }
                table { width:100%; border-collapse:collapse; }
                th, td { text-align:left; border-bottom:1px solid var(--line); padding:8px; vertical-align:top; }
                th { color:var(--accent); font-weight:600; }
                .empty { color:var(--muted); padding:18px; border:1px dashed var(--line); border-radius:6px; }
                .chips { display:flex; flex-wrap:wrap; gap:8px; margin:10px 0 0; padding:0; list-style:none; }
                .chips li { border:1px solid var(--line); background:var(--soft); border-radius:999px; padding:5px 9px; color:var(--muted); }
                .checklist { margin:0; padding-left:20px; }
                .checklist li { margin:6px 0; }
                footer { border-top:1px solid var(--line); margin-top:24px; padding-top:14px; }
                @media (max-width: 760px) { main { padding:18px; } .hero { grid-template-columns:1fr; } dl { grid-template-columns:1fr; } }
              </style>
            </head>
            <body>
            <main>
              <header>
                <div class="brand">{{logoMarkup}}<div>
                  <h1>{{Html(product)}} Capture Report</h1>
                  <div class="muted">{{Html(report.PageTitle)}} · {{Html(report.CreatedAt.ToString("yyyy-MM-dd HH:mm:ss zzz"))}}</div>
                  <ul class="chips"><li>{{Html(template.Name)}}</li><li>{{Html(template.Focus)}}</li></ul>
                </div></div>
              </header>
              <section class="panel summary">
                <h2>Executive Summary</h2>
                <p>{{Html(context.ExecutiveSummary)}}</p>
              </section>
              <section class="hero">
                <div class="panel">{{screenshotMarkup}}</div>
                <div class="panel">
                  <h2>Technical Summary</h2>
                  <dl>
                    {{Definition("URL", report.PageUrl)}}
                    {{Definition("Browser", report.Browser)}}
                    {{Definition("Remote port", report.RemotePort)}}
                    {{Definition("Target type", report.TargetType)}}
                    {{Definition("Profile", report.UsageProfile)}}
                    {{Definition("Element", report.TagName)}}
                    {{Definition("Selector", report.Selector)}}
                    {{Definition("Lens frame", $"{report.Frame.Width:0}x{report.Frame.Height:0} at {report.Frame.X:0},{report.Frame.Y:0}")}}
                    {{Definition("Center", $"{report.Frame.CenterX:0},{report.Frame.CenterY:0}")}}
                    {{Definition("Screen", $"{report.Frame.ScreenName} {report.Frame.ScreenWidth}x{report.Frame.ScreenHeight}")}}
                    {{Definition("Images", report.Images.Count.ToString(CultureInfo.InvariantCulture))}}
                  </dl>
                </div>
              </section>
              {{profileMarkup}}
              {{orderedSections}}
              <footer>{{Html(branding.FooterText)}}</footer>
            </main>
            </body>
            </html>
            """;
    }

    private static string BuildProfileHtml(CaptureReportProfileTemplate template)
    {
        return $"""
            <section class="panel">
              <h2>Profile Guidance</h2>
              <p>{Html(template.Focus)}</p>
              <h3>Priority Signals</h3>
              <ul>{string.Join(Environment.NewLine, template.PrioritySignals.Select(item => $"<li>{Html(item)}</li>"))}</ul>
              <h3>Review Checklist</h3>
              <ul class="checklist">{string.Join(Environment.NewLine, template.ReviewChecklist.Select(item => $"<li>{Html(item)}</li>"))}</ul>
              <h3>Recommended Next Steps</h3>
              <ul>{string.Join(Environment.NewLine, template.RecommendedNextSteps.Select(item => $"<li>{Html(item)}</li>"))}</ul>
            </section>
            """;
    }

    private static string BuildHtmlSection(CaptureReport report, string section, string imageRows, string notesMarkup)
    {
        var developer = section is "Technical" or "Attributes" or "CSS" or "DOM" or "Console";
        var markup = section switch
        {
            "Technical" => $$"""
                <h2>Technical Summary</h2>
                <dl>
                  {{Definition("URL", report.PageUrl)}}
                  {{Definition("Browser", report.Browser)}}
                  {{Definition("Remote port", report.RemotePort)}}
                  {{Definition("Target type", report.TargetType)}}
                  {{Definition("Profile", report.UsageProfile)}}
                  {{Definition("Element", report.TagName)}}
                  {{Definition("Selector", report.Selector)}}
                  {{Definition("Lens frame", $"{report.Frame.Width:0}x{report.Frame.Height:0} at {report.Frame.X:0},{report.Frame.Y:0}")}}
                  {{Definition("Center", $"{report.Frame.CenterX:0},{report.Frame.CenterY:0}")}}
                  {{Definition("Screen", $"{report.Frame.ScreenName} {report.Frame.ScreenWidth}x{report.Frame.ScreenHeight}")}}
                  {{Definition("Images", report.Images.Count.ToString(CultureInfo.InvariantCulture))}}
                </dl>
                """,
            "Notes" => $"<h2>Notes</h2>{notesMarkup}",
            "Issues" => $"<h2>Common Issues</h2><pre>{Html(string.IsNullOrWhiteSpace(report.CommonIssues) ? "No issue report found." : report.CommonIssues)}</pre>",
            "Attributes" => $"<h2>Attributes</h2><pre>{Html(report.Attributes)}</pre>",
            "CSS" => $"<h2>Computed CSS</h2><pre>{Html(report.ComputedCss)}</pre>",
            "DOM" => $"<h2>DOM</h2><pre>{Html(report.Dom)}</pre>",
            "Console" => $"<h2>Console</h2><pre>{Html(string.IsNullOrWhiteSpace(report.Console) ? "No console messages captured." : report.Console)}</pre>",
            "Images" => $"<h2>Image Resources</h2><table><thead><tr><th>Kind</th><th>Format</th><th>Shown</th><th>Natural</th><th>URL</th></tr></thead><tbody>{imageRows}</tbody></table>",
            _ => string.Empty
        };

        if (string.IsNullOrWhiteSpace(markup))
        {
            return string.Empty;
        }

        return developer
            ? $"<section class=\"panel\"><details><summary>Developer details · {Html(section)}</summary>{markup}</details></section>"
            : $"<section class=\"panel\">{markup}</section>";
    }

    private static string Definition(string key, string? value) => $"<dt>{Html(key)}</dt><dd>{Html(string.IsNullOrWhiteSpace(value) ? "-" : value)}</dd>";

    private static string Html(string? value) => WebUtility.HtmlEncode(value ?? string.Empty);

    private static string EscapeCssColor(string value)
    {
        return value.StartsWith("#", StringComparison.Ordinal) && value.Length is 4 or 7
            ? value
            : CaptureReportBranding.Default.AccentColor;
    }
}

public sealed class PdfReportRenderer
{
    public void Write(string path, CaptureReportRenderContext context)
    {
        SimplePdfReportWriter.Write(path, context.Report, RenderLines(context));
    }

    public IReadOnlyList<string> RenderLines(CaptureReportRenderContext context)
    {
        var report = context.Report;
        var template = context.Template;
        var lines = new List<string>
        {
            $"{(context.Branding.Enabled ? context.Branding.ProductName : "Julco")} Capture Report",
            $"Page: {report.PageTitle}",
            $"URL: {report.PageUrl}",
            $"Created: {report.CreatedAt:yyyy-MM-dd HH:mm:ss zzz}",
            $"Profile: {report.UsageProfile}",
            $"Profile focus: {template.Focus}",
            "Executive Summary:",
            context.ExecutiveSummary,
            $"Browser: {report.Browser} | Port: {report.RemotePort} | Target: {report.TargetType}",
            $"Element: {report.TagName} | Selector: {report.Selector}",
            $"Lens: {report.Frame.Width:0}x{report.Frame.Height:0} at {report.Frame.X:0},{report.Frame.Y:0} | Center: {report.Frame.CenterX:0},{report.Frame.CenterY:0}",
            $"Screen: {report.Frame.ScreenName} {report.Frame.ScreenWidth}x{report.Frame.ScreenHeight}",
            string.Empty,
        };

        lines.AddRange(BuildProfilePdfLines(template));
        foreach (var section in template.SectionOrder)
        {
            lines.AddRange(BuildPdfSection(report, section));
        }

        if (context.Branding.Enabled)
        {
            lines.Add(context.Branding.FooterText);
        }

        return lines
            .SelectMany(line => CaptureReportText.WrapLine(line.ReplaceLineEndings(" "), 96))
            .ToArray();
    }

    private static IReadOnlyList<string> BuildProfilePdfLines(CaptureReportProfileTemplate template)
    {
        return new[] { "Profile Guidance", $"Focus: {template.Focus}", "Priority Signals:" }
            .Concat(template.PrioritySignals.Select(item => $"- {item}"))
            .Concat(new[] { "Review Checklist:" })
            .Concat(template.ReviewChecklist.Select(item => $"- [ ] {item}"))
            .Concat(new[] { "Recommended Next Steps:" })
            .Concat(template.RecommendedNextSteps.Select(item => $"- {item}"))
            .Concat(new[] { string.Empty })
            .ToArray();
    }

    private static IReadOnlyList<string> BuildPdfSection(CaptureReport report, string section)
    {
        return section switch
        {
            "Technical" => new[]
            {
                "Developer details - Technical Summary",
                $"URL: {report.PageUrl}",
                $"Browser: {report.Browser} | Port: {report.RemotePort} | Target: {report.TargetType}",
                $"Element: {report.TagName} | Selector: {report.Selector}",
                $"Lens: {report.Frame.Width:0}x{report.Frame.Height:0} at {report.Frame.X:0},{report.Frame.Y:0}",
                $"Screen: {report.Frame.ScreenName} {report.Frame.ScreenWidth}x{report.Frame.ScreenHeight}",
                $"Images detected: {report.Images.Count}",
                string.Empty
            },
            "Notes" => new[] { "Notes", report.Notes.HasContent ? report.Notes.ShortSummary : "No notes added.", string.IsNullOrWhiteSpace(report.Notes.Observation) ? string.Empty : report.Notes.Observation, string.Empty },
            "Issues" => new[] { "Common Issues", string.IsNullOrWhiteSpace(report.CommonIssues) ? "No issue report found." : report.CommonIssues, string.Empty },
            "Attributes" => new[] { "Developer details - Attributes", report.Attributes, string.Empty },
            "CSS" => new[] { "Developer details - Computed CSS", report.ComputedCss, string.Empty },
            "DOM" => new[] { "Developer details - DOM preview", CaptureReportText.Shorten(report.Dom, 5000), string.Empty },
            "Console" => new[] { "Developer details - Console", string.IsNullOrWhiteSpace(report.Console) ? "No console messages captured." : report.Console, string.Empty },
            "Images" => new[]
            {
                "Image Resources",
                report.Images.Count == 0
                    ? "No image resources detected."
                    : string.Join(Environment.NewLine, report.Images.Take(30).Select(image => $"{image.Kind} {image.Format} shown {image.DisplayedWidth}x{image.DisplayedHeight}, natural {image.NaturalWidth}x{image.NaturalHeight}: {CaptureReportText.Shorten(image.Url, 120)}")),
                string.Empty
            },
            _ => Array.Empty<string>()
        };
    }
}

public static class CaptureReportText
{
    public static string Shorten(string? value, int maxLength)
    {
        if (string.IsNullOrWhiteSpace(value) || value.Length <= maxLength)
        {
            return value ?? string.Empty;
        }

        return value[..Math.Max(0, maxLength - 1)] + "...";
    }

    public static IEnumerable<string> WrapLine(string line, int maxLength)
    {
        if (string.IsNullOrWhiteSpace(line))
        {
            yield return string.Empty;
            yield break;
        }

        var remaining = line.Trim();
        while (remaining.Length > maxLength)
        {
            var splitAt = remaining.LastIndexOf(' ', Math.Min(maxLength, remaining.Length - 1));
            if (splitAt < maxLength / 2)
            {
                splitAt = maxLength;
            }

            yield return remaining[..splitAt].Trim();
            remaining = remaining[splitAt..].Trim();
        }

        if (remaining.Length > 0)
        {
            yield return remaining;
        }
    }
}
